name: preview deployement on vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches-ignore:
            - main
jobs:
    Deploy-production:
        runs-on: ubuntu-latest
        steps:

            -uses: actions/checkout@v3
            -name: Install vercel CLI
                run: npm install -g vercel
            -name: Pull vercel environment Information
                run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            -name: vercel build
                run: vercel  --token=${{ secrets.VERCEL_TOKEN }}
            -name: vercel deploy
                run: vercel deploy --prebuilt    --token=${{ secrets.VERCEL_TOKEN }}